db.url=jdbc:sqlserver://localhost:1433;databaseName=PolyPhone;encrypt=false;trustServerCertificate=true
db.username=sa
db.password=YourPassword123
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Email config (for OTP)
mail.host=smtp.gmail.com
mail.port=587
mail.username=Binhnttv00241@gmail.com
mail.password=zioy ddhw yhun thco
mail.from=polyphone@gmail.com

# Google OAuth2 Config
# T?o t?i: https://console.cloud.google.com/apis/credentials
# Lo?i: Web application
# Authorized redirect URIs: http://localhost:8080/PolyPhone/auth/google/callback
google.client.id=375177126769-lcquc4gj6q13ea6ilbksmbmajeendha2.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=https://polyphone-production.up.railway.app/auth/google/callback

# App configs
app.upload.dir=/uploads
app.name=PolyPhone
